name: API Linting and Testing
on:
  push:
    branches: [main]
    paths:
      - 'apps/api/**'
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |-
          cd apps/api
          yarn
      - name: Running linter
        run: |-
          cd apps/api
          yarn run lint
      - name: Running tests
        run: |-
          cd apps/api
          yarn test
